name: CI Workflow

on:
  push:
    branches:
      - main  # Solo se ejecuta en la rama principal
  pull_request:
    branches:
      - main  # Ejecuta pruebas para cada PR hacia la rama principal

jobs:
  test:
    runs-on: ubuntu-latest  # Máquina virtual para ejecutar el flujo

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # Actualizado a Node.js 20

    - name: Set up Python
      uses: actions/setup-python@v5  # Actualizado a Node.js 20
      with:
        python-version: '3.9'  # Ajusta según tu versión de Python

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Instalar dependencias del proyecto

    - name: Test app.py
      run: |
        python app.py --help  # Asegúrate de que app.py corre sin errores

    - name: Test notebook execution
      run: |
        pip install nbconvert  # Instalar nbconvert para ejecutar notebooks
        jupyter nbconvert --to notebook --execute notebooks/Boston_House_Price_Regression02.ipynb
